Repository apache/qpid-dispatch, pull requests merged in 2020-07, with the labels that each got.

#776 DISPATCH-1715 Fix -Wgnu-folding-constant in a test
  tests/hash_test.c
Labels: ready to merge

#777 DISPATCH-1716 Don't set -Wl,-z,defs in -fsanitize= builds with Clang
  .travis.yml
  src/CMakeLists.txt
Labels: ready to merge

#781 DISPATCH-1712 Proton enabled LTO on Clang, we need llvm-10-dev in CI
  .travis.yml
Labels: ready to merge

#779 DISPATCH-1720 Add GitHub Action to run console tests through npm
  .github/workflows/console.yaml
Labels: ready to merge

#294 DISPATCH-960 - Resolving service port when using http listener
  src/amqp.c
Labels: ready to merge

#783 DISPATCH-1725 Fix some Jest Web Console unittests
  console/react/package.json
  console/react/src/details/detailsTablePage.js
  console/react/src/details/detailsTablePage.test.js
  console/react/test_data/qdrService.mock.js
Labels: ready to merge

#784 DISPATCH-1725 Fix the ESLint failures
  console/react/package.json
  console/react/src/connect/connect-form.test.js
  console/react/src/details/createTablePage.test.js
Labels: ready to merge

#785 DISPATCH-1725 Fix the flaky tests in Jest Web Console suite
  console/react/src/overview/dashboard/inflightChart.test.js
  console/react/src/overview/dashboard/throughputChart.test.js
Labels: ready to merge

#786 NO-JIRA Configure .github/dependabot.yml
  .github/dependabot.yml
Labels: WIP

#801 DISPATCH-1726 Bump lodash from 4.17.15 to 4.17.19 in /console/react
  console/react/package-lock.json
Labels: dependencies
